credentials:
  usernames:
    admin:
      email: admin@org.com
      name: Admin User
      password: adminpass
    user:
      email: user@org.com
      name: Regular User
      password: userpass

cookie:
  expiry_days: 30
  key: some_random_key
  name: attendance_session

preauthorized:
  emails:
    - admin@org.com